- name: Configuring cart server 
  hosts: cart
  become: yes
  tasks: 
  - name: Disabling existing nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enabling nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Creating system user
    ansible.builtin.user:
      name: roboshop
      system: yes
      shell: /sbin/nologin
      comment: "roboshop system user"
      state: present
      home: /app

  - name: Removing /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Removing existing cart application
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: Downloading cart app file 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unzipping the file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install nodejs dependencies
    community.general.npm:
      path: /app
  
  - name: Creating systemd service for cart
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
        daemon_reload: yes

  - name: Start and enable service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes