- name: Configuring catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disabling nodejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: Creating a system user
    ansible.builtin.user:
      name: roboshop
      state: present
      system: true
      comment: "Roboshop system user"
      shell: /sbin/nologin
      home: /app

  - name: Remove /app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove existing catalogue application
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: To download the catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unzip a file 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install nodejs dependencies
    community.general.npm:
      path: /app

  - name: Create a systemd service for catalogue
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Creating mongo repo for client
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  
  - name: Connect to the mongodb catalog
    ansible.builtin.command: mongosh $MONGODB_HOST --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  - name: Printing catalogue output
    ansible.builtin.debug:
      msg: "Catalogue output is {{ catalogue_output }}"


  - name: Start and Enable catalogue service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
  
