- name: Configuring dispatch server
  hosts: dispatch
  become: yes
  tasks: 
  - name: Install golang
    ansible.builtin.package:
      name: golang
      state: present
  
  - name: Creating system user
    ansible.builtin.user:
      name: roboshop
      system: yes
      shell: /sbin/nologin
      comment: "roboshop system user"
      state: present
      home: /app

  - name: Removing /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Removing exiting dispatch application
    ansible.builtin.file:
      path: /tmp/dispatch.zip
      state: absent

  - name: Download latest dispatch application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip

  - name: Unzipping the file
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app

  - name: Installing dependencies
    ansible.builtin.command: "{{ item }}"
    loop:
    - go mod init dispatch
    - go get 
    - go build
    args:
      chdir: /app

  - name: Creating systemd dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon-reload: yes

  - name: Start and enable service
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes