- name: Configuring rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: Creating rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
  
  - name: Installing Rabbitmq server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: Start and Enable service 
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Settingup user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present