- name: Configuring User server
  hosts: user
  become: yes
  tasks: 
  - name: Disabling existing nodejs version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Creating a system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"
      home: /app
      state: present

  - name: Removing /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Removing existing user application
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: Downloading the user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: Unzipping the file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app
  
  - name: Creating systemd service for user
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable service
    ansible.builtin.service:
      name: user
      state: present
      enabled: yes